version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - images:/app/wwwroot/Images

  db:
    restart: always
    environment:
      POSTGRES_USER: CareerHubManager
      POSTGRES_PASSWORD: CareerHubManagerPassword
      POSTGRES_DB: CareerHub
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  images:
  database: